apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiKey.secretName }}
  labels:
    app: {{ .Release.Name }}
    environment: {{ .Values.environment }}
type: Opaque
data:
  {{ .Values.apiKey.secretKey }}: {{ .Values.apiKey.value | default "" | b64enc }} 