apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://your-aws-eks-cluster.region.eks.amazonaws.com
    certificate-authority-data: ${AWS_CLUSTER_CA_DATA}
  name: blaze-aws-prod
contexts:
- context:
    cluster: blaze-aws-prod
    namespace: production
    user: blaze-aws-prod
  name: blaze-aws-prod
current-context: blaze-aws-prod
preferences: {}
users:
- name: blaze-aws-prod
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
        - eks
        - get-token
        - --cluster-name
        - blaze-prod
        - --region
        - ${AWS_REGION} 